# MIT License
# Copyright (c) 2025 Lil5354
# EcoCheck Railway Configuration

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"
watchPatterns = ["**"]

[deploy]
startCommand = "node src/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

